schema_version = "1.0.0"

id = "bb_project_timer"
version = "0.3.0"
name = "BB Project Timer"
tagline = "Automatically tracks time spent working on a .blend file"
maintainer = "BB <riouxr@gmail.com>"
type = "add-on"

tags = ["System"]

blender_version_min = "4.5.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
